### ISSUE TITLE
woopshop.com is accepting NAV

### ISSUE THREAD

**Issue by hawafi** [navcoin/navcoin-org#108]
Hello,
woopshop.com is accepting NAV.
Regards

### Acceptance Criteria

Add merchant to stores listing

- [ ] Title
- [ ] Short Description
- [ ] Link
- [ ] Logo

**Comment by matt-auckland** [comment]
Is www.woopshop.com the correct url for your website? It seems to be broken

**Comment by hawafi** [comment]
https://www.woopshop.com 

use https instead of http

**Comment by roast-nav** [comment]
claimed by @roast-nav

**Comment by proletesseract** [comment]
Resolved by #210
