### ISSUE TITLE
merchant listing request

### ISSUE THREAD

**Issue by monovm** [navcoin/navcoin-org#152]
hi 
we want to be listed as merchant 
https://monovm.com
regards

**Comment by proletesseract** [comment]
Bounty Low shared by issues #218 #217 #216 #215 #152

**Comment by monovm** [comment]
navcoin/navcoin-org,


Your email to our support system could not be accepted because it was not recognized as coming from an email address belonging to one of our customers. If you need assistance, please email from the address you registered with us that you use to login to our client area.

**Comment by roast-nav** [comment]
Claimed.
