### ISSUE TITLE
Add Firo Solutions site to merchant section

### ISSUE THREAD

**Issue by FiroSolutions** [navcoin/navcoin-org#188]
### Description

Firo Solutions has started accepting NAV. Firo Solutions provides Vulnerability Management in the form of software as a service.

Website: https://firosolutions.com

### Motivation

Give more visibility to stores which accept NavCoin.

### Acceptance Criteria

Add merchant to stores listing

- [ ] Title
- [ ] Short Description
- [ ] Link
- [ ] Logo

**Comment by roast-nav** [comment]
claimed by @roast-nav

**Comment by proletesseract** [comment]
Resolved by #210
