### ISSUE TITLE
Add CoinZark to exchange listings

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#189]
CoinZark needs to be added to the buy-navcoin page.

https://www.coinzark.com/nav

### Acceptance Criteria

Add exchange to exchange listings

- [x] Title
- [x] Link
- [x] Logo (400x400)

**Comment by roast-nav** [comment]
claimed by @roast-nav

**Comment by proletesseract** [comment]
Resolved by https://github.com/navcoin/navcoin-org/pull/205
