### ISSUE TITLE
Add Print Ted to merchants page

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#190]
### Description

Print-ted has started accepting NavCoin. Please add them to the merchants list.

Website - https://print-ted.com/

### Motivation

Give more visibility to stores which accept NavCoin.

### Acceptance Criteria

Add merchant to stores listing

- [ ] Title
- [ ] Short Description
- [ ] Link
- [ ] Logo

**Comment by roast-nav** [comment]
claimed by @roast-nav

**Comment by proletesseract** [comment]
Resolved by #210
