### ISSUE TITLE
Do add Keyi Store to Merchants

### ISSUE THREAD

**Issue by saumyabratadutt** [navcoin/navcoin-org#197]
### Description

Keyi Store is an eCommerce store that accepts all cryptocurrencies. Keyi Store is accepting Nav Coin for their products. Do add Keyi Store.

Website - https://keyi.store

### Motivation

Give more visibility to stores which accept NavCoin.

### Acceptance Criteria

Add merchant to stores listing

- [ ] Title
- [ ] Short Description
- [ ] Link
- [ ] Logo

**Comment by roast-nav** [comment]
claimed by @roast-nav

**Comment by proletesseract** [comment]
Resolved by #210
