### ISSUE TITLE
Add SatoWallet Exchange

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#202]
SatoWallet has started exchanging NAV.

https://satowallet.com/

It needs to be added to the exchanges list

https://navcoin.org/en/buy-navcoin/

### Acceptance Criteria

Add exchange to exchange listings

- [ ] Title
- [ ] Link
- [ ] Logo (400x400)

**Comment by proletesseract** [comment]
claimed by @roast-nav

**Comment by roast-nav** [comment]
Hey @proletesseract are you working on this one or can I claim it?
