### ISSUE TITLE
Update the list of contributors to navcoin-core

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#212]
### Description
The list of contributors to NavCoin Core needs updating on the for-developers page.

https://navcoin.org/en/for-developers

should match this list -> https://github.com/navcoin/navcoin-core/graphs/contributors

### Motivation
Accurately reflect the efforts of new contributors to core.

### Acceptance Criteria

- [ ] List of contributors should match what is on the github contributors page.
- [ ] Should have image, github username, link to github profile for each.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or amended as necessary.

**Comment by roast-nav** [comment]
Can I claim this? Seems similar to what I've been doing.

**Comment by proletesseract** [comment]
@roast-nav looks like someone beat you to it. @amescarda to claim the bounty you should first comment on the issue and get it assigned to you.
