### ISSUE TITLE
Additional Italian Translations

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#231]
### Description
Some of the Italian translations are missing or incomplete

### Acceptance Criteria

Pages that need to be translated;

https://navcoin.org/it/
https://navcoin.org/it/why-navcoin/
https://navcoin.org/it/get-involved/
https://navcoin.org/it/bounties/
https://navcoin.org/it/wallets/

Some pages that are only partially translated:

https://navcoin.org/it/merchants/
https://navcoin.org/it/community-fund/

Add any additional acceptance criteria you think should be included to the list below.

- [ ] Description is satisfied.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or amended as necessary.

**Comment by roast-nav** [comment]
Combined with pr230

https://deploy-preview-230--navcoin.netlify.com/it/
https://deploy-preview-230--navcoin.netlify.com/it/bounties/
https://deploy-preview-230--navcoin.netlify.com/it/why-navcoin/
https://deploy-preview-230--navcoin.netlify.com/it/get-involved/
https://deploy-preview-230--navcoin.netlify.com/it/buy-navcoin/
https://deploy-preview-230--navcoin.netlify.com/it/merchants/
https://deploy-preview-230--navcoin.netlify.com/it/wallets/
https://deploy-preview-230--navcoin.netlify.com/it/community-fund/

**Comment by proletesseract** [comment]
resolved by #234
