### ISSUE TITLE
Add New Merchants & Exchanges

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#238]
### Description
Add two new additions to the merchants and exchanges pages.

**Exchanges**
Steathex.io
https://www.reddit.com/r/NavCoin/comments/cqq8nb/exchange_nav_at_stealthexio_an_anonymous_and/

**Merchants**
Blockashion.com
https://www.reddit.com/r/NavCoin/comments/cr3rcl/we_added_navcoin_httpblockchashioncom/

### Acceptance Criteria

Add any additional acceptance criteria you think should be included to the list below.

- [x] Check the merchants and exchanges actually have integrated NAV
- [x] Description is satisfied.
- [x] Changes display correctly on desktop / mobile.
- [x] Translations have been added or ammended as necessary.

**Comment by roast-nav** [comment]
Claimed :)

**Comment by roast-nav** [comment]
Merged
