### ISSUE TITLE
Dynamic GitHub Contributors

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-org#247]
Add React App to dynamically pull the GitHub contributors and some of their stats to the developers page.

https://navcoin.org/en/for-developers/#contributor-list

**Comment by Rohithgilla12** [comment]
Hey can I work on this issue?

**Comment by Rohithgilla12** [comment]
Do you have any design in mind?

**Comment by proletesseract** [comment]
covered by https://github.com/navcoin/navcoin-org/issues/291
