### ISSUE TITLE
Two spelling errors in community fund page

### ISSUE THREAD

**Issue by ToshiNakamot** [navcoin/navcoin-org#263]
### Description
*Highlighted in red*
Letter "P" is missing from "payment request"
Letters "c" and "t" are missing from "create payment request"
Was introduced in update 4.6 from memory

### Motivation
Looks more professional
Aids to aesthetics
Love NAV

### Acceptance Criteria
- [ ] Spelling changes display correctly on desktop. Mobile N/A
![Nav community fund spelling errors](https://user-images.githubusercontent.com/60483866/73484702-e5392f00-43f5-11ea-8398-83f04456b3c6.png)
.
- Don't know any languages other than English and Australian

**Comment by chasingkirkjufell** [comment]
Thank you for reporting. The issue has been addressed in PR 530 of NavCoin core. This is the repo for the website.

**Comment by ToshiNakamot** [comment]
No worries, sorry if i wasted your time. Only just started learning coding
and repositories, bit overwhelmed haha.
Wishing you all the best
Hugh
