### ISSUE TITLE
News for non english languages has not been updated for a while.

### ISSUE THREAD

**Issue by roast-nav** [navcoin/navcoin-org#286]
### Description
Some languages are missing translations from 4.6.0 and later.

### Acceptance Criteria
Copy the news files and relabel for respective languages. This pr will do that.
A later pr will hold the translations

**Comment by IgorsLV** [comment]
Where I can check the list of what needs to be translated and into what langauges?

**Comment by mxaddict** [comment]
@IgorsLV In this directory: https://github.com/navcoin/navcoin-org/tree/master/content/notices

Any article that only has a `*.en.md` file needs to be translated to other languages, `en` being the language, so if for example you wanted to translate the file to russian, you'd just create a file with the same name, except the ending would be `.ru.md`

**Comment by IgorsLV** [comment]
Thanks! Will check info in this link!
