### ISSUE TITLE
Fix broken/invalid links

### ISSUE THREAD

**Issue by KasteluKannu** [navcoin/navcoin-org#297]
Some links on https://navcoin.org/en/buy-navcoin/ need to be updated or deleted.

Links not working / Exchange not supporting Navcoin / Exchange shut down:

- Binance link is not working
- Equicex
- Changelly
- Bestrate --> Is that an exchange?
- Bitsquare
- Coindirect
- Crytex --> Directing to Bitminer
- Bitquist
- Altilly --> "hacked"
- Coin XTR --> Browser reporting possible security issue
- Coinzark --> Browser reporting possible security issue
- Zwaply
- CryptoWolf
- Satowallet
- Exscudo --> EON/NAV only trading pari with 0 volume
- Vertbase can be removed, it's now Sequior which is on the list

**Comment by chasingkirkjufell** [comment]
solved by #299
