### ISSUE TITLE
Add SwapSwop.io to buy-navcoin

### ISSUE THREAD

**Issue by antonegorov** [navcoin/navcoin-org#325]
### Description
Adding a SwapSwop.io exchanger to the Buy navcoin list (PR #324)

### Motivation
Good crypto projects are good. The more such projects, the better. The project has been running for more than 1 year.

### Acceptance Criteria

- [ ] Description is satisfied.
- [x] Changes display correctly on desktop / mobile.
- [x] Translations have been added or ammended as necessary.

**Comment by chasingkirkjufell** [comment]
PR merged

**Comment by antonegorov** [comment]
@chasingkirkjufell, thank you

**Comment by chasingkirkjufell** [comment]
@antonegorov you are very welcome. :)
