### ISSUE TITLE
Review and finish Hungarian translation of the GUI

### ISSUE THREAD

**Issue by urbalazs** [navcoin/navcoin-org#329]
### Description
The completeness of the Hungarian translation is 33.9% on [Transifex](https://www.transifex.com/navcoin/navcoin-core/). I already requested to join to the Hungarian language team. I'm waiting for approval.

### Motivation
I am translating free and open source software in my free time. Additionally, I am also interested in crypto currencies. Unfortunately I have no possibility to buy expensive hardware for mining, so I was looking for a crypto currency that uses Proof-of-Stake instead of Proof-of-Work. Now I have found Navcoin. In order to start mining, I need a small amount of Navcoin. The easiest way for me to get some is the bounty program. I hope, I can reward some Navcoin for my translation and I can start discover this world.

### Acceptance Criteria

Add any additional acceptance criteria you think should be included to the list below.

- [x] Description is satisfied.
- [x] Changes display correctly on desktop / mobile.
- [x] Translations have been added or ammended as necessary.

**Comment by chasingkirkjufell** [comment]
approved your request. welcome to navcoin :)

**Comment by urbalazs** [comment]
Hungarian translation is done, you can find it on Transifex. How can I get some bounty for my work?

**Comment by urbalazs** [comment]
@chasingkirkjufell any news about this topic? I need some NAV to start staking, so a bounty would be very welcomed for my work.

**Comment by urbalazs** [comment]
@chasingkirkjufell ping

**Comment by chasingkirkjufell** [comment]
@urbalazs sorry for the delay. we'll have a look.

**Comment by urbalazs** [comment]
@chasingkirkjufell ping :)

**Comment by urbalazs** [comment]
@chasingkirkjufell ping

**Comment by urbalazs** [comment]
@aguycalled I'm sorry to bother you but I cannot contact with @chasingkirkjufell
As you can see, I have finished the Hungarian translation of the GUI and I hope to reward some bounty for my work. I'm still new in Navcoin, so maybe this could be my address to receive the bounty:

```
$ bin/navcoin-cli listreceivedbyaddress 1 true
[
  {
    "address": "NX2Y5ULRXsaCZ85gK1nfM9GY8DF2cA162H",
    "account": "",
    "amount": 0.00000000,
    "confirmations": 0,
    "label": "",
    "txids": [
    ]
  }
]
```

Can you please help me?

**Comment by chasingkirkjufell** [comment]
hi @urbalazs I am trying to see how we can verify your work. I'll try to sort out the bounty in the meantime.

**Comment by urbalazs** [comment]
@chasingkirkjufell ping :)

**Comment by chasingkirkjufell** [comment]
@urbalazs sent you some NAV. Thanks for the work. It turns out that we actually don't really have a bounty for translations but I think we should probably have one in the future. 

Now, you mentioned you're interested in staking the coins. I'd suggest using NavPool, NavCash, or Next Mobile. These are all community pools that would be great for staking smaller amounts with a fee.
