### ISSUE TITLE
Shortcode zig_section improvement

### ISSUE THREAD

**Issue by craigmacgregor** [NAVCoin/navcoin-org#69]
Given the `paragraphText` element generally has HTML markup in it, i would suggest pulling that out to be the body of the shortcode.

This way the markup can be indented and formatted more easily than having it injected from a single line string.

Can't remember exactly how it works, but here's a pseudocode example.

```
{{< zig_section
    titleText="My Title"
>}}
    <p>
        My formatted paragraph text can go here
    </p>
{{< /zig_section >}}
```

Then in the shortcode HTML snippet there's a way to capture that content and inject it.

**Comment by matt-auckland** [comment]
Fixed by #93
