### ISSUE TITLE
Remove font awesome

### ISSUE THREAD

**Issue by matt-auckland** [NAVCoin/navcoin-org#89]
Why:

Font awesome is only used in a couple places on the site and we're pulling in a big file for just a couple icons. If we can remove it then the site will load faster for users.

How:
- Go through the site and locate all the places font awesome is used
- Replace all these with actual images, ideally .png or .svg files. Don't link external images, add the images to the theme folder
- Remove font awesome
- Check the the site isn't missing any thing and all font awesome icons have been replaced.

**Comment by Spotts9** [comment]
would like to take this one one.

**Comment by matt-auckland** [comment]
Awesome, go hard
