### ISSUE TITLE
Add site to NAVCoin merchant section

### ISSUE THREAD

**Issue by celestinee** [navcoin/navcoin-org#96]
http://toys4sex.com.au

It is our pleasure to be able to introduce you to Toys4Sex, Australia’s Online Adult store retailer intended for men and women. Toys4Sex comes with a specially selected range of products that has made its mark within the Australian adult market place.

![t4s-newlogo-larger](https://user-images.githubusercontent.com/22674265/46919060-500af080-cf8e-11e8-8928-b7f6d1fd3f3e.png)

**Comment by roast-nav** [comment]
Claimed.
